name: dyslexia_colour_app
description: A new Flutter project for dyslexic students colour game.
publish_to: 'none' # Remove this line if you publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Packages we need
  tflite_flutter: ^0.12.1
  image: ^3.3.0
  camera: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/emotion_model_cafe.tflite
    - assets/test_images/sample_face.jpg
